


import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsReseller: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


};

export default sidebarsReseller;