// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebarsAdmin: SidebarsConfig = {
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Admin Guide',
//       link: {
//         type: 'generated-index',
//       },
//       items: [
//         {
//           type: 'autogenerated',
//           dirName: '.',
//         },
//       ],
//     },
//   ],
// };

// export default sidebarsAdmin;


import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsAdmin: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


};

export default sidebarsAdmin;

