import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsReseller: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Reseller Guide',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    },
  ],
};

export default sidebarsReseller;